---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: orangecloudfoundry/orange-cf-bosh-cli


inputs:
  - name: pcf-prometheus-pipeline
  - name: om-bosh-creds

run:
  path: pcf-prometheus-pipeline/ci/tasks/test-bosh.sh