resource_types:
- name: bosh-creds
  type: docker-image
  source:
    repository: mkuratczyk/bosh-creds-resource
    tag: 1.4
- name: bosh-deploy
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource

resources:
- name: pcf-prometheus-pipeline
  type: git
  source:
    uri: https://github.com/freakin/pcf-prometheus-pipeline.git
    branch: master
- name: pcf-bosh-creds
  type: bosh-creds
  source:
    pcf_opsman_admin_username: ((pcf_opsman_admin_username))
    pcf_opsman_admin_password: ((pcf_opsman_admin_password))
    opsman_url: ((opsman_url))
    external_bosh_address: ((external_bosh_address))
    external_bosh_client: ((external_bosh_client))
    external_bosh_client_secret: ((external_bosh_client_secret))
    external_bosh_ca_cert: ((external_bosh_ca_cert))

jobs:
- name: test
  plan:
  - get: pcf-prometheus-pipeline
  - get: pcf-bosh-creds
  - task: test-bosh
    file: pcf-prometheus-pipeline/pipeline/tasks/test-bosh.yml